name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: quay.io/podman/stable
      volumes:
        - cardapi:/app

    strategy:
      matrix:
        framework: [angular, vue, flask]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Podman volume
        run: podman volume create cardapi-code

      - name: Copy code to Podman volume
        run: podman cp . cardapi-code:/app

      - name: Build and test
        run: podman run --rm -v cardapi-code:/app:ro,z myimage npm run build

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: myregistry.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Podman image to container registry
        run: podman push cardapi-code:${{ matrix.framework }} myregistry.com/cardapi-code:${{ matrix.framework }}
